Rename function to refer to gen_interval
epiverse-trace/epichains pull request #116
Opened 2023-11-29 17:16 UTC by jamesmbaazam

This PR closes #109 by:

- Renaming the `serials_dist` argument to `gen_interval`
- Revising previous wordings referring to the serial interval to use "generation interval" instead.

2023-11-30 14:12 UTC, sbfnk requested changes
Yes!

I would prefer `generation_interval` to `gen_interval`. Do you think it's too much to type?

Or as a compromise we could call it `generation_time` (only 3 characters more than `gen_interval`...) which would have the benefit of being the same as in EpiNow2.

2023-11-30 14:55 UTC, jamesmbaazam commented
> Or as a compromise we could call it generation_time (only 3 characters more than gen_interval...) which would have the benefit of being the same as in EpiNow2.

I'm a big fun of {EpiNow2}, so I'll go with this. I think there is a similar notion in {epiparameter}, so +1. 

Will make the change.

2023-12-01 16:53 UTC, jamesmbaazam commented on vignettes/projecting_incidence.Rmd
> +and standard deviation, $SD [S]$, we can use the following parametrisation:
@sbfnk Could you take a quick look at this rewording for me? Thanks.

2023-12-01 19:58 UTC, sbfnk commented on vignettes/epichains.Rmd
> +Here is a quick example where we simulate an outbreak in a population of size $1000$. We assume individuals have a poisson offspring distribution with mean, $\text{lambda} = 1$, and generation time o
```suggestion
Here is a quick example where we simulate an outbreak in a population of size $1000$. We assume individuals have a poisson offspring distribution with mean, $\text{lambda} = 1$, and fixed generation time of $3$:
```

2023-12-01 20:06 UTC, sbfnk reviewed
All looking good - we're now using both generation "time" and "interval". Perhaps that's fine as they're used interchangeably in the literature but I was wondering if it would be worth doing a search/replace "generation interval" -> "generation time" everywhere and clarify in just one point that they're the same (I made a suggestion where).

2023-12-01 20:06 UTC, sbfnk commented on vignettes/projecting_incidence.Rmd
> +generation interval, that is, the time between successive cases.
```suggestion
use the serial interval and interpret the simulated case data to represent
symptom onset.
```

I wasn't quite sure what you meant so attempted to rephrase - does this make sense?

2023-12-01 22:17 UTC, jamesmbaazam commented on vignettes/epichains.Rmd
> +Here is a quick example where we simulate an outbreak in a population of size $1000$. We assume individuals have a poisson offspring distribution with mean, $\text{lambda} = 1$, and generation time o
Thanks.

2023-12-01 22:46 UTC, merged